// Curated player nicknames keyed by URL slug. Add more as needed.
export const PLAYER_NICKNAMES: Record<string, string> = {
  "nikola-jokic":            "The Joker",
  "giannis-antetokounmpo":   "Greek Freak",
  "lebron-james":            "King James",
  "stephen-curry":           "Chef Curry",
  "kevin-durant":            "Slim Reaper",
  "kawhi-leonard":           "The Klaw",
  "luka-doncic":             "Luka Magic",
  "shai-gilgeous-alexander": "SGA",
  "joel-embiid":             "The Process",
  "victor-wembanyama":       "The Alien",
  "anthony-edwards":         "Ant-Man",
  "jayson-tatum":            "Deuce",
  "jaylen-brown":            "JB",
  "devin-booker":            "D-Book",
  "donovan-mitchell":        "Spida",
  "ja-morant":               "JM12",
  "trae-young":              "Ice Trae",
  "damian-lillard":          "Dame Time",
  "zion-williamson":         "Zanos",
  "tyrese-haliburton":       "Hali",
  "paolo-banchero":          "Po",
  "chet-holmgren":           "Slim Reaper Jr",
  "scottie-barnes":          "Scoot",
  "cade-cunningham":         "Cade",
  "evan-mobley":             "Mobes",
  "jalen-brunson":           "Captain Brunson",
  "karl-anthony-towns":      "KAT",
  "bam-adebayo":             "Bam",
  "pascal-siakam":           "Spicy P",
  "russell-westbrook":       "Brodie",
  "james-harden":            "The Beard",
  "demar-derozan":           "DDR",
  "rudy-gobert":             "The Stifle Tower",
  "klay-thompson":           "Klay",
  "alperen-sengun":          "Alpi",
  "lamelo-ball":             "Melo",
  "tyrese-maxey":            "Maxey",
  "paolo-banchero-2":        "Po",
};
